import React, {useEffect, useState} from 'react'
import {createRoot} from 'react-dom/client'
import './style.css'

type Session = {id:string,title:string|null,agent:string,device_name:string,last_activity:string|null,message_count:number,run_count:number,profile:string,cwd:string|null}
type Message = {id:string,role:string,body:string|null,content_state:string,occurred_at:string|null,source_char_count:number|null}
type Run = {id:string,status:string,start_at:string|null,end_at:string|null,duration_ms:number|null,model:string|null}
type Metric = {id:string,value:number|null,unit:string,quality_note:string}
type Device = {id:string,name:string,os:string,environment:string,last_heartbeat:string|null,pending_count:number}
type Source = {id:string,device_id:string,agent:string,profile:string,last_error:string|null,last_scan:string|null}

async function request<T>(path:string, options:RequestInit={}, csrf?:string):Promise<T>{
  const headers:Record<string,string>={'Content-Type':'application/json',...(options.headers as Record<string,string>||{})}
  if(csrf && options.method && options.method!=='GET')headers['x-awb-csrf']=csrf
  const response=await fetch(path,{...options,headers,credentials:'same-origin'})
  if(!response.ok)throw new Error(`${response.status}: ${(await response.text()).slice(0,220)}`)
  return response.json()
}
const dateLocal=()=>new Date().toLocaleDateString('en-CA')
const time=(v:string|null)=>v?new Date(v).toLocaleString('zh-CN'): '未知'
const num=(v:number|null,unit='')=>v===null?'未知':`${new Intl.NumberFormat('zh-CN').format(v)}${unit}`
const metric=(values:Metric[],id:string)=>values.find(x=>x.id===id)?.value??null

function App(){
  const [csrf,setCsrf]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
  const [view,setView]=useState<'overview'|'sessions'|'devices'>('overview'); const [date,setDate]=useState(dateLocal());
  const [sessions,setSessions]=useState<Session[]>([]); const [selected,setSelected]=useState<string|null>(null);
  const [detail,setDetail]=useState<{session:Session,items:Message[],runs:Run[],files:Record<string,unknown>[],next_cursor:string|null}|null>(null)
  const [stats,setStats]=useState<Metric[]>([]); const [devices,setDevices]=useState<Device[]>([]); const [sources,setSources]=useState<Source[]>([])
  const [query,setQuery]=useState(''); const [search,setSearch]=useState<{items:{id:string,session_id:string,excerpt:string,title:string|null}[]}|null>(null)
  const [pairCode,setPairCode]=useState(''); const [registration,setRegistration]=useState({id:'',device_id:'',agent:'codex',profile:'default',content_policy:'stats_only'})
  const [loading,setLoading]=useState(false)
  useEffect(()=>{request<{csrf:string}>('/auth/me').then(x=>setCsrf(x.csrf)).catch(()=>{})},[])
  async function refresh(){if(!csrf)return;setLoading(true);setError('');try{
    const [a,b,c,d]=await Promise.all([
      request<{items:Session[]}>('/v1/sessions?limit=200'),
      request<{metrics:Metric[]}>(`/v1/stats?day=${date}&tz=${encodeURIComponent(Intl.DateTimeFormat().resolvedOptions().timeZone)}`),
      request<{items:Device[]}>('/v1/devices'),request<{items:Source[]}>('/v1/sources')])
    setSessions(a.items);setStats(b.metrics);setDevices(c.items);setSources(d.items)
  }catch(e){setError(String(e))}finally{setLoading(false)}}
  useEffect(()=>{void refresh()},[csrf,date])
  useEffect(()=>{if(!selected){setDetail(null);return}request<typeof detail>(`/v1/sessions/${selected}/events`).then(x=>setDetail(x)).catch(e=>setError(String(e)))},[selected])
  async function doLogin(e:React.FormEvent){e.preventDefault();setError('');try{const x=await request<{csrf:string}>('/auth/login',{method:'POST',body:JSON.stringify({password})});setCsrf(x.csrf);setPassword('')}catch(e){setError('登录失败：'+String(e))}}
  async function doSearch(e:React.FormEvent){e.preventDefault();if(query.trim().length<2)return;try{setSearch(await request(`/v1/search?q=${encodeURIComponent(query.trim())}`));setView('sessions')}catch(e){setError(String(e))}}
  async function makePair(){try{const x=await request<{code:string}>('/v1/pairing-codes',{method:'POST'},csrf);setPairCode(x.code)}catch(e){setError(String(e))}}
  async function register(e:React.FormEvent){e.preventDefault();try{await request('/v1/sources/register',{method:'POST',body:JSON.stringify(registration)},csrf);setError('');void refresh()}catch(e){setError(String(e))}}
  if(!csrf)return <main className="login"><div className="loginCard"><div className="brandIcon">✳</div><h1>跨 Agent 工作台</h1><p>登录后查看各设备的 Codex 与 Hermes 活动。</p><form onSubmit={doLogin}><label>管理员密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button type="submit">登录</button></form>{error&&<div className="error" role="alert">{error}</div>}<small>首次使用请在服务器运行 <code>uv run awb init-owner</code></small></div></main>
  return <div className="shell"><aside className="sidebar"><div className="logo"><span className="brandIcon">✳</span><span>Agent<br/>Workbench</span></div><nav aria-label="主导航"><button className={view==='overview'?'active':''} onClick={()=>setView('overview')}>▦　总览</button><button className={view==='sessions'?'active':''} onClick={()=>setView('sessions')}>☷　会话</button><button className={view==='devices'?'active':''} onClick={()=>setView('devices')}>◉　设备与设置</button></nav><div className="sidebarFoot"><span className="liveDot"/> 单用户本地工作台<br/><small>仅展示已采集证据</small></div></aside>
    <main className="main"><header className="top"><div><div className="eyebrow">WORKSPACE / {view==='overview'?'OVERVIEW':view==='sessions'?'SESSIONS':'SETTINGS'}</div><h1>{view==='overview'?'活动总览':view==='sessions'?'会话记录':'设备与设置'}</h1></div><div className="topActions"><span>{loading?'同步中…':'已连接'}</span><button onClick={()=>void refresh()}>刷新</button></div></header>{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}
    {view==='overview'&&<><section className="controls"><label>查看日期 <input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><span className="muted">统计采用浏览器时区 · 数据不完整时显示未知</span></section><section className="cards"><Card title="活动时间" value={num(metric(stats,'active_wall_ms')===null?null:Math.round((metric(stats,'active_wall_ms')||0)/60000),' 分钟')} hint="并行轮次按时间并集计算"/><Card title="完成轮次" value={num(metric(stats,'completed_count'))} hint="仅已发现的轮次"/><Card title="人类输入" value={num(metric(stats,'human_input_chars'),' 字')} hint="Unicode 字符数"/><Card title="耗时 P95" value={num(metric(stats,'duration_p95_ms')===null?null:Math.round((metric(stats,'duration_p95_ms')||0)/1000),' 秒')} hint="仅有可信边界的完成轮次"/></section><section className="columns"><div className="panel"><div className="panelHead"><h2>最近会话</h2><button className="textButton" onClick={()=>setView('sessions')}>查看全部 →</button></div>{sessions.length? sessions.slice(0,8).map(s=><SessionRow key={s.id} s={s} onClick={()=>{setSelected(s.id);setView('sessions')}}/>):<Empty text="尚无活动。请先配对设备并登记来源。"/>}</div><div className="panel"><div className="panelHead"><h2>设备状态</h2><button className="textButton" onClick={()=>setView('devices')}>管理 →</button></div>{devices.length?devices.map(d=><div className="deviceRow" key={d.id}><span className="deviceIcon">⌘</span><div><b>{d.name}</b><small>{d.os} · {d.last_heartbeat?'最后在线 '+time(d.last_heartbeat):'等待首次心跳'}</small></div><span className="badge">{d.pending_count} 待传</span></div>):<Empty text="尚未配对设备"/>}</div></section></>}
    {view==='sessions'&&<div className="three"><section className="listPane"><form className="search" onSubmit={doSearch}><input placeholder="搜索已保存的消息正文" value={query} onChange={e=>setQuery(e.target.value)}/><button>搜索</button></form>{search&&<><div className="listTitle">搜索结果 <button className="textButton" onClick={()=>setSearch(null)}>清除</button></div>{search.items.map(r=><button className="result" key={r.id} onClick={()=>setSelected(r.session_id)}><b>{r.title||'未命名会话'}</b><span>{r.excerpt}</span></button>)}</>}<div className="listTitle">所有会话 · {sessions.length}</div>{sessions.length?sessions.map(s=><SessionRow key={s.id} s={s} active={selected===s.id} onClick={()=>setSelected(s.id)}/>):<Empty text="还没有会话；设备在线后会自动出现。"/>}</section><section className="detailPane">{detail?<><div className="detailHead"><div className="eyebrow">{detail.session.agent.toUpperCase()} · {detail.session.profile}</div><h2>{detail.session.title||'未命名会话'}</h2><p className="muted">{detail.session.cwd||'未记录工作目录'}</p></div><div className="detailTabs"><span>对话 {detail.items.length}</span><span>轮次 {detail.runs.length}</span><span>文件 {detail.files.length}</span></div><div className="timeline">{detail.items.map(m=><article className="message" key={m.id}><div className="messageMeta"><b>{m.role==='user'?'用户':m.role==='assistant'?'Agent':m.role}</b><time>{time(m.occurred_at)}</time></div>{m.body?<p>{m.body}</p>:<p className="muted">{m.content_state==='stats_only'?'仅统计：正文未采集':'正文未保存'}{m.source_char_count!==null?` · 原文 ${m.source_char_count} 字`:''}</p>}</article>)}{detail.items.length===0&&<Empty text="此会话尚无可显示的消息"/>}</div></>:<div className="selectPrompt">从左侧选择会话，查看对话、轮次与文件证据。</div>}</section><aside className="contextPane"><h3>活动证据</h3>{detail?<><div className="contextLabel">轮次</div>{detail.runs.map(r=><div className="run" key={r.id}><b>{r.status}</b><small>{r.model||'模型未知'}</small><small>{time(r.start_at)} · {r.duration_ms===null?'耗时未知':`${Math.round(r.duration_ms/1000)} 秒`}</small></div>)}<div className="contextLabel">关联文件</div>{detail.files.map((f,i)=><div className="file" key={i}>{String(f.relative_path||f.native_path||'未知路径')}</div>)}</>:<p className="muted">选择会话后显示</p>}</aside></div>}
    {view==='devices'&&<div className="settingsGrid"><section className="panel"><h2>已配对设备</h2>{devices.length?devices.map(d=><div className="deviceRow" key={d.id}><span className="deviceIcon">⌘</span><div><b>{d.name}</b><small>{d.id}</small><small>{d.environment}</small></div></div>):<Empty text="尚无设备"/>}<button onClick={makePair}>生成 10 分钟配对码</button>{pairCode&&<div className="pairCode" aria-label="配对码">{pairCode}</div>}</section><section className="panel"><h2>已登记来源</h2>{sources.map(s=><div className="sourceRow" key={s.id}><b>{s.agent} · {s.profile}</b><small>{s.id}</small><small>{s.last_error?'错误：'+s.last_error:s.last_scan?'最近扫描 '+time(s.last_scan):'尚未扫描'}</small></div>)}<h3>登记来源</h3><p className="muted">先在采集端运行 add-source，复制终端显示的 ID 到这里。确认采集策略后再启动采集。</p><form className="register" onSubmit={register}><label>来源 ID<input value={registration.id} onChange={e=>setRegistration({...registration,id:e.target.value})} required/></label><label>设备 ID<select value={registration.device_id} onChange={e=>setRegistration({...registration,device_id:e.target.value})} required><option value="">选择设备</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Agent<select value={registration.agent} onChange={e=>setRegistration({...registration,agent:e.target.value})}><option value="codex">Codex</option><option value="hermes">Hermes</option></select></label><label>Profile<input value={registration.profile} onChange={e=>setRegistration({...registration,profile:e.target.value})}/></label><label>采集策略<select value={registration.content_policy} onChange={e=>setRegistration({...registration,content_policy:e.target.value})}><option value="stats_only">仅统计</option><option value="full_content">正文脱敏后采集</option><option value="excluded">排除</option></select></label><button type="submit">确认登记</button></form></section></div>}
    </main></div>
}
function Card({title,value,hint}:{title:string,value:string,hint:string}){return <div className="card"><small>{title}</small><strong>{value}</strong><span>{hint}</span></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function SessionRow({s,onClick,active}:{s:Session,onClick:()=>void,active?:boolean}){return <button className={'sessionRow '+(active?'selected':'')} onClick={onClick}><span className="agentGlyph">{s.agent==='codex'?'C':'H'}</span><span className="sessionText"><b>{s.title||'未命名会话'}</b><small>{s.device_name} · {s.agent} · {time(s.last_activity)}</small></span><span className="count">{s.message_count}</span></button>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
